
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `course`;

CREATE TABLE `course`(`cid` INT(11) NOT NULL AUTO_INCREMENT, 
`name` VARCHAR(20) DEFAULT NULL, 
`title` VARCHAR(20) DEFAULT NULL, PRIMARY KEY (`cid`)) 
ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET = latin1;

DROP TABLE IF EXISTS `student`;

CREATE TABLE `student`(`sid` INT(11) NOT NULL AUTO_INCREMENT, 
`name` VARCHAR(25) DEFAULT NULL, 
`address` VARCHAR(25)DEFAULT NULL, 
`age` VARCHAR(30) DEFAULT NULL,PRIMARY KEY(`sid`)) 
ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `student_course`;

CREATE TABLE `student_course` (
`sid` INT(30) DEFAULT NULL,
`cid` INT(15) DEFAULT NULL,
PRIMARY KEY(`sid`, `cid`),
CONSTRAINT `FK_Student_idx`
FOREIGN KEY(`sid`)
REFERENCES `student` (`sid`)
ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `FK_Course_idx`
FOREIGN KEY(`cid`)
REFERENCES `course` (`cid`)
ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS=1;